using BungieApiHelper.Entity.Definition.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BungieApiHelper.Entity.Definition.Sockets {
    public class DestinyPlugSetDefinition : DestinyDefinition {
        /// <summary>
        /// If you want to show these plugs in isolation, these are the display properties for them.
        /// </summary>
        public DestinyDisplayPropertiesDefinition displayProperties { get; set; }
        /// <summary>
        /// This is a list of pre-determined plugs that can be plugged into this socket, without the character having the plug in their inventory.
        /// </summary>
        /// <remarks>
        /// If this list is populated, you will not be allowed to plug an arbitrary item in the socket: you will only be able to choose from one of these reusable plugs.
        /// </remarks>
        public IEnumerable<object> reusablePlugItems { get; set; }
        /// <summary>
        /// Mostly for our debugging or reporting bugs, BNet is making "fake" plug sets in a desperate effort to reduce socket sizes.
        /// </summary>
        /// <remarks>
        /// If this is true, the plug set was generated by BNet: if it looks wrong, that's a good indicator that it's bungie.net that fucked this up.
        /// </remarks>
        public bool isFakePlugSet { get; set; }
    }
}
